FROM golang:1.23-alpine as build

WORKDIR /build

COPY . .

RUN GOOS=linux GOARCH=arm64 go build -ldflags "-s -w" -o /hello-web ./cmd/web

FROM alpine as release

# Install ca-certificates using apk
RUN apk --no-cache add ca-certificates

# Copy your CA certificate
COPY certs/ca.crt /usr/local/share/ca-certificates/custom-ca.crt

# Update CA certificates
RUN update-ca-certificates

COPY --from=build /hello-web /hello-web

EXPOSE 3000
ENTRYPOINT ["/hello-web"]
